# Generated by Django 3.0 on 2019-12-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191216_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='cust_rate',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='customers',
            name='number_of_jars_taken_in_a_month',
            field=models.IntegerField(default=0),
        ),
    ]
